# Generated by Django 4.0.5 on 2022-07-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('mobile_code', models.IntegerField()),
                ('tag', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('finish_dt', models.DateTimeField()),
                ('text', models.CharField(default='', max_length=255)),
                ('tag', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_dt', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mailing')),
            ],
        ),
    ]
