# Generated by Django 4.0.5 on 2022-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mobile_code',
            field=models.IntegerField(default=10),
        ),
    ]
