# Generated by Django 4.0.5 on 2022-07-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_mailing_mobile_code_alter_mailing_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing_dt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('MAILED', 'Доставлено успешно'), ('LOST', 'Потеряно')], max_length=255),
        ),
        migrations.CreateModel(
            name='Delivery_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt1', models.DateTimeField()),
                ('dt2', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.message')),
            ],
        ),
    ]
