# Generated by Django 4.0.5 on 2022-07-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_client_mobile_code_delete_delivery_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('MAILED', 'Успешно'), ('LOST', 'Потеряно')], max_length=255),
        ),
    ]
